version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: hiragana-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: hiragana
    ports:
      - "3306:3306"  # Porta 3307 no host para n√£o conflitar com MySQL local
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot@123"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hiragana-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hiragana?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
    networks:
      - minha_rede
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  minha_rede:
    driver: bridge